CREATE DATABASE REGISTRATE;
USE REGISTRATE;
DROP TABLE IF EXISTS EDUCANDO;
CREATE TABLE EDUCANDO
(
    CODEDU INT AUTO_INCREMENT PRIMARY KEY ,
    DNIEDU CHAR(8) NOT NULL,
    NOMEDU VARCHAR(60) NOT NULL,
    APEEDU VARCHAR(60) NOT NULL,
    SEXEDU CHAR(1) NOT NULL,
    TELEDU CHAR(9) NOT NULL,
    DISEDU VARCHAR(70) NOT NULL,
    PROEDU VARCHAR(70) NOT NULL,
    DEPEDU VARCHAR(70) NOT NULL,
    DIREDU VARCHAR(70) NOT NULL,
    GRAEDU VARCHAR(70) NOT NULL,
    FECEDU DATE NOT NULL
    );

/* MODIFICAMOS EL CAMPO DISEDU*/
ALTER TABLE EDUCANDO
    ADD CONSTRAINT DISTRITO CHECK(LENGTH(DISEDU)> 3);

ALTER TABLE EDUCANDO
    ADD CONSTRAINT PROVINCIA CHECK(LENGTH(PROEDU)> 3);
ALTER TABLE EDUCANDO
    ADD CONSTRAINT DEPARTAMENTO CHECK(LENGTH(DEPEDU)> 3);
    
/* MODIFICAMOS EL CAMPO SEXCLI PARA QUE ACEPTE CONDICIONES DE SUS VALORES */
ALTER TABLE EDUCANDO
    ADD CONSTRAINT SEXO_VALIDO CHECK(SEXEDU = 'M' OR SEXEDU = 'F');
    
SHOW COLUMNS IN EDUCANDO;


INSERT INTO EDUCANDO
(DNIEDU, NOMEDU, APEEDU, SEXEDU, TELEDU, DISEDU, PROEDU, DEPEDU, DIREDU, GRAEDU, FECEDU)
VALUES
('77889955', 'ALBERTO', 'SOLANO PARIONA', 'MASCULINO', '998456321', 'NUEVO IMPERIAL', 'CAÑETE', 'LIMA', 'URB.SANTA LUISA', 'SECUNDARIA', '1980/09/05');

SELECT*FROM EDUCANDO;